version: '3.8'

services:
  backend:
    build: .
    container_name: express-backend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_CNN=mongodb://mongo:27017/calendardb
      - SECRET_JWT_SEED=eSTO_ES_Una_pAlabra12309039120
      - GOOGLE_CLIENT_ID=95608793243-dnlebjrskg0hu8onp7f24vdl62ul5jc4.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=tu_secreto_de_google
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`timegrid-timegrid-unlqgb-9dafa6-145-223-74-28.traefik.me`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    networks:
      - web

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=calendardb
      - MONGO_INITDB_ROOT_USERNAME=calendardb
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - SECRET_JWT_SEED=${SECRET_JWT_SEED}
    ports:
      - "27017:27017"
    networks:
      - web

networks:
  web:
    external: true